[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = ["npm install -g pnpm@8", "pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["npx prisma generate --schema=./prisma/schema.prisma", "pnpm run build"]

[start]
cmd = "node apps/api/dist/main.js"
