[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = ["npm install -g pnpm@8", "pnpm install"]

[phases.build]
cmds = ["pnpm run build"]

[start]
cmd = "cd apps/api && node dist/main.js"
